### ISSUE TITLE
What happens when we short a PWM output?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#261]
1. Unlikely to happen if liquid gets on the heater pcb
2. May blow up the MOSFET
3. May shutdown the Rpi (if using 5v rail)

**Comment by VitorFrost** [comment]
What MOSFET are you using? I was thinking about ideal transistors to control my 12V LED strips intensity.

**Comment by CamDavidsonPilon** [comment]
For the PWM outputs, we are using BSS316NH6327XTSA1. However, for our LED system (only powering four 5mm LEDs), we have a DAC + LED driver circuit.
