### ISSUE TITLE
Do we need these configs for the pioreactor?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#317]
Found in the `/boot/config.txt` on the Raspberry Pi. 

**Are these needed for our purpose? Can we safely turn them off (comment them out)? Does turning them off give us any performance gains?**

```
dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

```

**Comment by kellytr** [comment]
Looks like you already configured the following: 
gpu_mem=16
dtoverlay=disable-bt
dtparam=audio=off
camera_auto_detect=0
display_auto_detect=0
hdmi_blanking=2
dtparam=act_led_trigger=none
dtparam=act_led_activelow=off
dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4
dtparam=i2c_arm=on
