### ISSUE TITLE
LED automation cannot be set to fractions of an hour

### ISSUE THREAD

**Issue by c-bun** [Pioreactor/pioreactor#416]
Hello! I'm interested in setting up an LED automation to be on for 6 minutes (0.1 hours) and off for 54 minutes (0.9 hours) when I input these times as an LED automation, the LED will stay on and never turn off. I have tested this with other fractions of hours and have never obtained the desired result.

Could we add the capability to use fractions of hours? Or at least throw an error in the LED automation field when a user inputs a fraction?

**Comment by CamDavidsonPilon** [comment]
Hi @c-bun, this sounds like a bug more than a feature. Are you trying to set up a light/dark cycle like this? 

<img width="693" alt="Screenshot 2023-07-11 at 2 37 33 PM" src="https://github.com/Pioreactor/pioreactor/assets/884032/1199af49-1cca-4caa-8f1b-c26610794c30">

Or, have you written your own automation with Python?

**Comment by c-bun** [comment]
Yes, that is exactly what I am trying to do. When I put in 0.1 and 0.9 respectively I have found that the light does not blink as expected, it will stay on for the full hour.

**Comment by CamDavidsonPilon** [comment]
I see. We originally envisioned users thinking about on/off cycles in integer hours, not fractions. But if you need fractions, we'll support it! I'll extend this to use fractions in the next release. 

For now, here's a solution (if you're comfortable with working on the RPi command line):

1. Add the [linked Python file](https://gist.github.com/CamDavidsonPilon/555e7dfa5417d8590387a27275c7e1f8) to `~/.pioreactor/plugins/light_dark_cycle_frac.py`. 
2. Test it's working by running the following on the command line:
```
pio run led_control --automation-name light_dark_cycle_frac --light_duration_hours 0.9 --dark_duration_hours 0.1 --duration 1 --light_intensity 20
```
3. ctrl-c to exit. 
4. If that works, you can add it to the UI as well. On your leader Pioreactor, add the [linked file](https://gist.github.com/CamDavidsonPilon/2a54e34936ed582e8f0e9b10161d11c1) to `~/.pioreactor/plugins/ui/contrib/automations/led/light_dark_cycle_frac.yaml`
Wait a minute, and try refreshing your UI:

<img width="676" alt="Screenshot 2023-07-11 at 4 13 13 PM" src="https://github.com/Pioreactor/pioreactor/assets/884032/cc9c82a5-c9bc-4f00-a265-d47999743d3a">

**Comment by c-bun** [comment]
Awesome! Thanks @CamDavidsonPilon. I should be fine adding it via the command line. I appreciate your help!

**Comment by c-bun** [comment]
@CamDavidsonPilon your code was not running as expected for me, so I rewrote to work by-the-minute [on this gist](https://gist.github.com/c-bun/9e88f314c1a3002837f7fc7fcb54fd9d). This seems to work for me!

**Comment by CamDavidsonPilon** [comment]
My solution was this weird hours vs. minutes hybrid. I love your rewrite! Can I add it to the core app?

**Comment by c-bun** [comment]
Of course! Yay!
