### ISSUE TITLE
Temperature control: change failed because of 'TemperatureController' object has no attribute 'temperature'

### ISSUE THREAD

**Issue by kellytr** [Pioreactor/pioreactor#487]
Started a new experiment. Ran temperature automation only_record_temperature(). Within 30 seconds, switched over to thermostat automation and recieved the following error messages. There was no data collected on the Temperature chart on Overview. It seems that when the first data point is recorded. this error doesn't occur anymore. 

![image](https://github.com/Pioreactor/pioreactor/assets/106164999/f4c623f3-9c23-4cde-b156-c32c31cfbdad)

![image](https://github.com/Pioreactor/pioreactor/assets/106164999/8aa37acd-d2dd-4eca-bb9b-6bc2c877458d)

**Comment by CamDavidsonPilon** [comment]
Fixed in next release - race condition
