### ISSUE TITLE
Rpi starts activity in profile much slower than others in the cluster; when cancelled before rpi starts running, doesn't cleanup correctly

### ISSUE THREAD

**Issue by kellytr** [Pioreactor/pioreactor#490]
A leader/worker and three other workers are part of a cluster. Worker3 has a slower running rpi. I started a basic profile that turned on stirring at 400 rpm, the turned it off after 1.2 minutes.

When profile began, stirring on leader, worker1, worker2 started. I cancelled the profile before worker3 started stirring. The first three pioreactors cancelled the profile/stirring action correctly, while worker3 did not and stirring activated soon after. Stirring did not shut off on worker3.

**Comment by CamDavidsonPilon** [comment]
I think this is a non-issue since we don't recommend the RPi Zeros anymore
