### ISSUE TITLE
Removing/unassigning/inactivating a leader from experiment with a running profile will end the profile

### ISSUE THREAD

**Issue by kellytr** [Pioreactor/pioreactor#492]

**Comment by CamDavidsonPilon** [comment]
Thinking more about this. How does one end an experiment profile? Either:

1. It ends naturally
2. The user stops it early from the /profiles page
3. The experiment is ended (via the UI).

**Comment by CamDavidsonPilon** [comment]
This is solved with the introduction of more logic in the JobManager. We went with a "make exp profiles long-running". A user must explicitly end a profile. 

(Next release)
